### PR TITLE
Await promise in TimeoutPolicy execute call using TimeoutStrategy.Agressive

### PR DESCRIPTION
**Pull request by ekillops**

### CODE REVIEW

**Comment by connor4312** [comment]
Can you update the test case for this? Should be able to catch it by adding an `await delay(0)` before this line:

https://github.com/connor4312/cockatiel/blob/7704a2537d0fb9423712b6276fa89c171b371946/src/TimeoutPolicy.test.ts#L33

**Comment by ekillops** [comment]
Yeah, I can add that.

**Comment by ekillops** [comment]
The test is updated and I verified that your addition causes the test to fail when the promise is not awaited

**Comment by connor4312** [comment]
Thanks! `npm run fmt` will fix up formatting, this this is good to merge 🚀

**Comment by ekillops** [comment]
Fixed

**Pull request merged**
